import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";
import { ClerkProvider, Show, SignInButton, SignUpButton } from '@clerk/nextjs'
import { Button } from "@/components/ui/button";
import UserDropdown from "./user-dropdown";
import { Toaster } from "@/components/ui/sonner"
import PageContainer from "@/components/page-container";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={poppins.variable}>
        <body className="min-h-dvh flex flex-col">
          <nav className="bg-primary text-white">
            <PageContainer size="wide" className="h-16 sm:h-20 flex items-center justify-between">
              <Link href='/' className="font-bold text-lg sm:text-2xl flex gap-2 items-center">
                <ChartColumnBigIcon className="text-lime-500" />
                <span className="tracking-tight">NextCash</span>
              </Link>
              <div className="flex items-center gap-1 sm:gap-2">
                <Show when="signed-out">
                  <Button asChild variant="link" className="text-white px-2 sm:px-3">
                    <SignInButton />
                  </Button>

                  <Button asChild variant="link" className="text-white px-2 sm:px-3">
                    <SignUpButton />
                  </Button>
                </Show>

                <Show when="signed-in">
                  <UserDropdown />
                </Show>
              </div>
            </PageContainer>
          </nav>
          <main className="flex-1">
            {children}
          </main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
